version: '3'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      DATABASE_HOST: "db"
      DATABASE_PORT: 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  bundle_cache:
  mysql_data:
